name: Node.js CI

on:
  push:
    branches: [ "deployment" ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: pm2 restart all
